redmine_questions-0_0_7-light/redmine_questions/config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html

resources :questions do
  collection do
    get :autocomplete_for_topic
    get :topics
  end
  member do
    get :vote
  end
end

match "issues/:issue_id/move_to_forum/:board_id" => "questions#convert_issue", :via => [:get, :post]

redmine_questions-0_0_7-light/redmine_questions/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  unloadable

  before_filter :find_optional_project, :only => [:autocomplete_for_topic, :topics]
  before_filter :find_optional_board, :only => [:autocomplete_for_topic, :topics]
  before_filter :find_topic, :authorize, :only => :vote
  before_filter :find_topics, :only => [:topics, :autocomplete_for_topic]

  helper :questions
  if Redmine::VERSION.to_s > '2.1'
    helper :boards
  end
  include QuestionsHelper

  def index
    @boards = Board.visible.includes(:last_message => :author).includes(:messages).order(:project_id)
    # show the board if there is only one
    if @boards.size == 1
      @board = @boards.first
      redirect_to project_board_url(@board, :project_id => @board.project)
    else
      render "boards/index"
    end
  end

  def topics
  end

  def vote
    User.current.voted_for?(@topic) ? @topic.dislike(User.current.becomes(Principal)) : @topic.like(User.current.becomes(Principal))
    respond_to do |format|
      format.html { redirect_to_referer_or {render :text => (watching ? 'Vote added.' : 'Vote removed.'), :layout => true}}
    end
  end

  def autocomplete_for_topic
    render :layout => false
  end

  def convert_issue
    issue = Issue.visible.find(params[:issue_id])
    board = Board.visible.find(params[:board_id])
    message = Message.new
    message.author = issue.author
    message.created_on = issue.created_on
    message.board = board
    message.subject = issue.subject
    message.content = issue.description.blank? ? issue.subject : issue.description
    message.watchers = issue.watchers
    message.add_watcher(issue.author)
    message.attachments = issue.attachments
    issue.journals.select{|j| !j.notes.blank?}.each do |journal|
      reply = Message.new
      reply.author = journal.user
      reply.created_on = journal.created_on
      reply.subject = "Re: #{message.subject}"
      reply.content = journal.notes
      reply.board = board
      message.children << reply
    end
    if message.save
      issue.destroy if params[:destroy]
      redirect_to board_message_path(board, message)
    else
      redirect_back_or_default({:controller => 'issues', :action => 'show', :id => issue})
    end

  end

private

  def find_topics
    seach = params[:q] || params[:topic_search]

    columns = ["subject", "content"]
    tokens = seach.to_s.scan(%r{((\s|^)"[\s\w]+"(\s|$)|\S+)}).collect{|m| m.first.gsub(%r{(^\s*"\s*|\s*"\s*$)}, '')}.uniq.select {|w| w.length > 1 }
    tokens = [] << tokens unless tokens.is_a?(Array)
    token_clauses = columns.collect {|column| "(LOWER(#{column}) LIKE ?)"}
    sql = (['(' + token_clauses.join(' OR ') + ')'] * tokens.size).join(' AND ')
    find_options = [sql, * (tokens.collect {|w| "%#{w.downcase}%"} * token_clauses.size).sort]

    scope = Message.joins(:board).where({})
    scope = scope.where("#{Message.table_name}.parent_id IS NULL")
    scope = scope.where(["#{Board.table_name}.project_id = ?", @project.id]) if @project
    scope = scope.where(["#{Message.table_name}.board_id = ?", @board.id]) if @board
    scope = scope.where(find_options) unless tokens.blank?
    scope = scope.visible.includes(:board).order("#{Message.table_name}.updated_on DESC")

    @topic_count = scope.count
    @limit =  per_page_option
    @topic_pages = Paginator.new(self, @topic_count, @limit, params[:page])
    @offset = @topic_pages.current.offset
    scope = scope.limit(@limit).offset(@offset)
    scope = scope.tagged_with(params[:tag]) unless params[:tag].blank?
    @topics = scope
  end

  def find_topic
    @topic = Message.visible.find(params[:id]) unless params[:id].blank?
    @board = @topic.board
    @project = @board.project
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def find_optional_board
    @board = Board.visible.find(params[:board_id]) unless params[:board_id].blank?
    @project = @board.project if @board
    allowed = User.current.allowed_to?({:controller => params[:controller], :action => params[:action]}, @project, :global => true)
    allowed ? true : deny_access
  rescue ActiveRecord::RecordNotFound
    render_404
  end



end

redmine_questions-0_0_7-light/redmine_questions/app/helpers/questions_helper.rb
module QuestionsHelper
  def vote_tag(object, user, options={})
    content_tag("span", vote_link(object, user))
  end

  def vote_link(object, user)
    return '' unless user && user.logged? && user.respond_to?('voted_for?')
    voted = user.voted_for?(object)
    url = {:controller => 'questions', :action => 'vote', :id => object}
    link_to((voted ? l(:button_questions_unvote) : l(:button_questions_vote)), url, 
      :class => (voted ? 'icon icon-vote' : 'icon icon-unvote'))

  end  

end

redmine_questions-0_0_7-light/redmine_questions/app/views/boards/index.html.erb
<%= render :partial => "questions/forums" %>

redmine_questions-0_0_7-light/redmine_questions/app/views/boards/show.html.erb
<%= board_breadcrumb(@board) %>

<div class="board details">
<div class="contextual">
<%= link_to_if_authorized l(:label_message_new),
                          {:controller => 'messages', :action => 'new', :board_id => @board},
                          :class => 'icon icon-add',
                          :onclick => 'showAndScrollTo("add-message", "message_subject"); return false;' %>
<%= content_tag('span', watcher_link(@board, User.current), :id => 'watcher') %>
</div>

<div id="add-message" style="display:none;">
<% if authorize_for('messages', 'new') %>
<h2><%= link_to h(@board.name), :controller => 'boards', :action => 'show', :project_id => @project, :id => @board %> &#187; <%= l(:label_message_new) %></h2>
<%= form_for @message, :url => {:controller => 'messages', :action => 'new', :board_id => @board}, :html => {:multipart => true, :id => 'message-form'} do |f| %>
  <%= render :partial => 'messages/form', :locals => {:f => f} %>
  <p><%= submit_tag l(:button_create) %>
  <%= preview_link({:controller => 'messages', :action => 'preview', :board_id => @board}, 'message-form') %> |
  <%= link_to l(:button_cancel), "#", :onclick => '$("#add-message").hide(); return false;' %></p>
<% end %>
<div id="preview" class="wiki"></div>
<% end %>
</div>

<h2><%=h @board.name %></h2>
<p class="subtitle"><%=h @board.description %></p>

<div class="filters">
  <%= form_tag({:controller => "questions", :action => "topics" }, :method => :get,  :id => "query_form") do %>
    <%= hidden_field_tag('project_id', @project.to_param) if @project %>
    <%= hidden_field_tag('board_id', @board.to_param) if @board %>
    <% no_filters = true %>

    <%= text_field_tag(:topic_search, params[:topic_search], :autocomplete => "off", :class => "questions-search", :placeholder => l(:label_questions_search) ) %>
    <%= javascript_tag "observeSearchfield('topic_search', 'topics_list', '#{ escape_javascript(autocomplete_for_topic_questions_path(:project_id => @project, :board_id => @board)) }')" %>


  <% end %>

</div>

</div>

<div id="topics_list" >
<%= render :partial => "questions/topic_list" %>
</div>

<% other_formats_links do |f| %>
  <%= f.link_to 'Atom', :url => {:key => User.current.rss_key} %>
<% end %>


<% content_for :sidebar do %>
  <%= render :partial => "questions/notice" %>
  <%= render :partial => "questions/tag_cloud" %>
  <%= render :partial => "questions/voted_topics" %>
<% end %>

<% html_title @board.name %>

<% content_for :header_tags do %>
    <%= auto_discovery_link_tag(:atom, {:format => 'atom', :key => User.current.rss_key}, :title => "#{@project}: #{@board}") %>
  <%= javascript_include_tag :questions, :plugin => 'redmine_questions'  %>
<% end %>

redmine_questions-0_0_7-light/redmine_questions/app/views/messages/_form.html.erb
<%= error_messages_for 'message' %>
<% replying ||= false %>

<div class="box">
<!--[form:message]-->
<p style=<%= "display:none;" if replying %> ><label for="message_subject"><%= l(:field_subject) %></label><br />
  <%= f.text_field :subject, :style => "width: 80%;", :id => "message_subject" %>
<% unless replying %>

  <% if @message.safe_attribute? 'sticky' %>
    <%= f.check_box :sticky %> <%= label_tag 'message_sticky', l(:label_board_sticky) %>
  <% end %>
  <% if @message.safe_attribute? 'locked' %>
    <%= f.check_box :locked %> <%= label_tag 'message_locked', l(:label_board_locked) %>
  <% end %>
<% end %>
</p>

<% if !replying && !@message.new_record? && @message.safe_attribute?('board_id') %>
  <p><label><%= l(:label_board) %></label><br />
  <%= f.select :board_id, boards_options_for_select(@message.project.boards) %></p>
<% end %>

<p>
<%= label_tag "message_content", l(:description_message_content), :class => "hidden-for-sighted" %>
<%= f.text_area :content, :cols => 80, :rows => 15, :class => 'wiki-edit', :id => 'message_content' %></p>
<%= wikitoolbar_for 'message_content' %>
<!--[eoform:message]-->

<% if !replying && @message.safe_attribute?('tag_list') %>
<p>
  <label for="message_tag_list"><%= l(:field_questions_tags) %></label><br />
  <%= render :partial => 'questions/form_tags' %>
</p>
<% end %>

<p><%= l(:label_attachment_plural) %><br />
<%= render :partial => 'attachments/form', :locals => {:container => @message} %></p>
</div>

redmine_questions-0_0_7-light/redmine_questions/app/views/messages/edit.html.erb
<%= board_breadcrumb(@message) %>

<h2><%= avatar(@topic.author, :size => "24") %><%=h @topic.subject %></h2>

<%= form_for @message, {
               :as => :message,
               :url => {:action => 'edit'},
               :html => {:multipart => true,
                         :id => 'message-form',
                         :method => :post}
          } do |f| %>
  <%= render :partial => 'form',
             :locals => {:f => f, :replying => !@message.parent.nil?} %>
  <%= submit_tag l(:button_save) %>
  <%= preview_link({:controller => 'messages', :action => 'preview', :board_id => @board, :id => @message}, 'message-form') %>
<% end %>
<div id="preview" class="wiki"></div>

redmine_questions-0_0_7-light/redmine_questions/app/views/messages/show.html.erb
<%= board_breadcrumb(@message) %>

<div class="contextual">
    <%= content_tag('span', watcher_link(@topic, User.current), :id => 'watcher') %>
    <% voted = User.current.voted_for?(@topic) %>
    <%= link_to(
          voted ? l(:button_questions_unvote) : l(:button_questions_vote),
          {:controller => 'questions', :action => 'vote', :id => @topic},
          :class => 'icon ' + (voted ? 'icon-vote' : 'icon-unvote')
        ) if User.current.allowed_to?(:vote_messages, @project) %>

    <%= link_to(
          l(:button_quote),
          {:action => 'quote', :id => @topic},
          :remote => true,
          :method => 'get',
          :class => 'icon icon-comment',
          :remote => true) if !@topic.locked? && authorize_for('messages', 'reply') %>
    <%= link_to(
          l(:button_edit),
          {:action => 'edit', :id => @topic},
          :class => 'icon icon-edit'
        ) if @message.editable_by?(User.current) %>
    <%= link_to(
          l(:button_delete),
          {:action => 'destroy', :id => @topic},
          :method => :post,
          :data => {:confirm => l(:text_are_you_sure)},
          :class => 'icon icon-del'
         ) if @message.destroyable_by?(User.current) %>
</div>

<div class="message details">
    <h2><%=h @topic.subject %></h2>
    <%= avatar(@topic.author, :size => "32") %>
    <p class="author"><%= link_to_user @topic.author %><br>
       <%= l(:label_questions_added_time, :value => time_tag(@topic.created_on)).html_safe %>
    </p>
    <div class="wiki">
      <%= textilizable(@topic, :content) %>
    </div>
    <%= link_to_attachments @topic, :author => false %>

</div>
<br />

<% unless @replies.empty? %>
<h3 class="comments"><%= l(:label_reply_plural) %> (<%= @reply_count %>)</h3>
<% @replies.each do |message| %>
  <div class="message reply" id="<%= "message-#{message.id}" %>">
    <div class="contextual">
    <% liked = User.current.voted_for?(message) %>
    <%= link_to(
          message.count_votes_up > 0 ? "(#{message.count_votes_up})" : "",
          {:controller => 'questions', :action => 'vote', :id => message},
          :class => 'vote icon ' + (liked ? 'icon-vote' : 'icon-unvote')
        ) if true || User.current.allowed_to?(:vote_messages, @project) %>
      <%= link_to(
            image_tag('comment.png'),
            {:action => 'quote', :id => message},
            :remote => true,
            :method => 'get',
            :title => l(:button_quote)) if !@topic.locked? && authorize_for('messages', 'reply') %>
      <%= link_to(
            image_tag('edit.png'),
            {:action => 'edit', :id => message},
            :title => l(:button_edit)
          ) if message.editable_by?(User.current) %>
      <%= link_to(
            image_tag('delete.png'),
            {:action => 'destroy', :id => message},
            :method => :post,
            :data => {:confirm => l(:text_are_you_sure)},
            :title => l(:button_delete)
          ) if message.destroyable_by?(User.current) %>
    </div>
  <% if Setting.gravatar_enabled?  %>
  <div class="avatar">
     <%= message_avatar = avatar(message.author, :size => "32") %>
  </div>
  <% end %>
  <div class="reply-details <%= 'use-avatar' unless message_avatar.blank? %>">
    <h4 class="author"><%= authoring message.created_on, message.author %></h4>
    <div class="wiki"><%= textilizable message, :content, :attachments => message.attachments %></div>
    <%= link_to_attachments message, :author => false %>
  </div>
  </div>
<% end %>
<p class="pagination"><%= pagination_links_full @reply_pages, @reply_count, :per_page_links => false %></p>
<% end %>

<% if !@topic.locked? && authorize_for('messages', 'reply') %>
<p><%= toggle_link l(:button_reply), "reply", :focus => 'message_content' %></p>
<div id="reply" style="display:none;">
<%= form_for @reply, :as => :reply, :url => {:action => 'reply', :id => @topic}, :html => {:multipart => true, :id => 'message-form'} do |f| %>
  <%= render :partial => 'form', :locals => {:f => f, :replying => true} %>
  <%= submit_tag l(:button_submit) %>
  <%= preview_link({:controller => 'messages', :action => 'preview', :board_id => @board}, 'message-form') %>
<% end %>
<div id="preview" class="wiki"></div>
</div>
<% end %>


<% content_for :sidebar do %>
  <h3><%= l(:label_questions_message) %></h3>
  <ul class="question-meta">
    <li class="votes icon icon-vote">
      <%= l(:label_questions_votes, :count => @topic.count_votes_up - @topic.count_votes_down ) %>
    </li>
    <li class="views icon icon-view">
      <%= l(:label_questions_views, :count => @topic.view_count ) %>
    </li>
    <% unless @topic.tags.blank? %>
    <li class="tags icon icon-tag">
      <%=
        @topic.tags.collect do |tag|
          link_to tag, {:controller => "questions", :action => "topics", :project_id => @project, :tag => tag.name}
        end.join(', ').html_safe
      %>
    </li>
    <% end %>
  </ul>

  <h3><%= l(:label_questions_related_messages) %></h3>
  <ul class="related-topics">
    <%#  Board.all.map(&:topics).flatten.first(5).each do |topic| %>
    <% tokens = @topic.subject.strip.scan(%r{((\s|^)"[\s\w]+"(\s|$)|\S+)}).collect {|m| m.first.gsub(%r{(^\s*"\s*|\s*"\s*$)}, '')} || "" %>
    <% if ActiveRecord::VERSION::MAJOR >= 4 %>
      <% related_topics = Message.where(tokens.map{ |t| "subject LIKE '%#{t}%'" }.join(' OR ')).to_a.compact if tokens %>
    <% else %>
      <% related_topics = Message.search(tokens, @project, :limit => 5)[0].select{|m| m != @topic && m.parent_id == nil }.compact if tokens %>
    <% end %>
    <% related_topics.each do |topic| %>
    <li class="related-topic">
      <%= link_to h(topic.subject), { :controller => 'messages', :action => 'show', :board_id => topic.board, :id => topic } %>
    </li>
    <% end if related_topics %>
  </ul>


<% end %>

<% html_title @topic.subject %>

redmine_questions-0_0_7-light/redmine_questions/app/views/settings/_questions.html.erb
<p><label for="settings_sidebar_message"><%= l(:label_questions_sidebar_message) %></label>
<%= text_area_tag 'settings[sidebar_message]', @settings[:sidebar_message], :class => 'wiki-edit', :rows => 5 %>
</p>