easy_gantt/config/routes.rb
scope '(projects/:project_id)' do
  resource :easy_gantt, :controller => 'easy_gantt', :only => [:index] do
    member do
      get 'issues'
      get 'projects'
      put 'relation/:id(.:format)', :to => 'easy_gantt#change_issue_relation_delay', :as => 'relation'
    end
  end
end

easy_gantt/app/models/easy_gantt/easy_gantt_issue_query.rb
module EasyGantt
  class EasyGanttIssueQuery < IssueQuery

    def from_params(params)
      build_from_params(params)
    end

    def entity
      Issue
    end

    def entity_scope
      scope = Issue.visible
      if Project.column_names.include? 'easy_baseline_for_id'
        scope = scope.where(Project.table_name => {easy_baseline_for_id: nil})
      end
      scope
    end

    def create_entity_scope(options={})
      entity_scope.includes(options[:includes]).references(options[:includes]).preload(options[:preload]).where(statement)
    end

    def entities(options={})
      create_entity_scope(options).order(options[:order])
    end

    def to_partial_path
      'easy_gantt/easy_queries/show'
    end

    def default_columns_names
      columns_names = [:subject, :priority, :assigned_to]
      #columns_names.unshift(:project) if project.nil?
      columns_names
    end

  end

end

easy_gantt/app/controllers/easy_gantt_controller.rb
class EasyGanttController < ApplicationController
  accept_api_auth :index, :issues, :projects, :change_issue_relation_delay

  before_filter :find_optional_project
  before_filter :find_query, :only => [:issues, :projects]
  before_filter :authorize, :if => Proc.new{ @project.present? }
  before_filter :authorize_global, :if => Proc.new{ @project.nil? }

  menu_item :easy_gantt

  helper :queries
  helper :easy_gantts
  helper :custom_fields
  if defined?(EasyExtensions)
    helper :easy_query
    include EasyQueryHelper
  end
  include SortHelper

  def index
    redirect_to :issues
  end

  def issues
    if Setting.rest_api_enabled != "1"
      render_error :message => l(:no_rest_api, :scope => [:easy_gantt, :errors])
    else
      find_start_date
      find_end_date

      respond_to do |format|
        format.html { render(:layout => !request.xhr?) }
        format.api do
          find_fixed_versions
          find_projects
          find_relations
          find_entities
        end
      end
    end
  end

  def projects
    project_scope = Project.column_names.include?('easy_is_easy_template') ? Project.where(:easy_is_easy_template => false) : Project
    project_ids = @query.create_entity_scope.distinct.pluck(:project_id)

    @projects = project_scope.visible.preload(:enabled_modules).has_module(:issue_tracking).where(Project.table_name => { :id => project_ids })

    respond_to do |format|
      format.api
    end
  end

  def change_issue_relation_delay
    return render_403 unless User.current.allowed_to?(:manage_issue_relations, @project, :global => true)
    find_relation
    @relation.update_attributes(:delay => params[:delay])
    respond_to do |format|
      format.api { @relation.valid? ? render_api_ok : render_api_errors(@relation.errors.full_messages) }
    end
  end

  private

  def find_relation
    @relation = IssueRelation.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def query_class
    EasyGantt::EasyGanttIssueQuery
  end

  def find_query
    if defined?(EasyIssueGanttQuery)
      params[:force_use_from_session] = true
      retrieve_query(EasyIssueGanttQuery, :use_session_store => true)
      @query.export_formats = {}
      @query.display_filter_group_by_on_index = false
      @query.display_filter_settings_on_index = false
      @query.group_by = nil
    else
      find_query_from_params_or_session
    end
  end

  def find_query_from_params_or_session
    if !params[:query_id].blank?
      cond = 'project_id IS NULL'
      cond << " OR project_id = #{@project.id}" if @project
      @query = query_class.where(cond).find(params[:query_id])
      raise ::Unauthorized unless @query.visible?
      @query.project = @project
      session[:query] = {:id => @query.id, :project_id => @query.project_id}
      sort_clear
    elsif params[:set_filter] || session[:query].nil? || session[:query][:project_id] != (@project ? @project.id : nil)
      # Give it a name, required to be valid
      @query = query_class.new(:name => '_')
      @query.project = @project
      @query.build_from_params(params)
      session[:query] = {:project_id => @query.project_id, :filters => @query.filters, :group_by => @query.group_by, :column_names => @query.column_names}
    else
      # retrieve from session
      @query = nil
      @query = query_class.find_by_id(session[:query][:id]) if session[:query][:id]
      @query ||= query_class.new(:name => '_', :filters => session[:query][:filters], :group_by => session[:query][:group_by], :column_names => session[:query][:column_names])
      @query.project = @project
    end
    @query.group_by = nil
  end

  def find_fixed_versions
    if @project
      scope = if Setting.display_subprojects_issues?
        Version.where("id IN (#{@project.shared_versions.select(:id).to_sql}) OR id IN (#{@project.rolled_up_versions.visible.select(:id).to_sql})").uniq
      else
        @project.shared_versions
      end
      @fixed_versions = scope.reorder(:effective_date)
    else
      fixed_version_scope = Version.visible.open
    end

    if Project.column_names.include?('easy_is_easy_template')
      @fixed_versions = fixed_version_scope.where(Project.table_name => {:easy_is_easy_template => false}).reorder(:effective_date) if fixed_version_scope
    else
      @fixed_versions = fixed_version_scope.reorder(:effective_date) if fixed_version_scope
    end

    if !@project && Project.column_names.include?('easy_baseline_for_id')
      @fixed_versions = @fixed_versions.where(Project.table_name => {easy_baseline_for_id: nil})
    end
  end

  def find_projects
    project_scope = Project
    if Project.column_names.include?('easy_is_easy_template')
      project_scope = project_scope.where(:easy_is_easy_template => false)
    end
    @projects = project_scope.visible.has_module(:issue_tracking).where(:id => @query.create_entity_scope(:includes => [:project, :status, :assigned_to, :fixed_version, :tracker, :priority, :custom_values]).pluck(:project_id))
  end

  def find_relations
    @relations = IssueRelation.joins(:issue_from => [:project, :status]).where(@query.statement)

    if !@project && Project.column_names.include?('easy_baseline_for_id')
      @relations = @relations.where(Project.table_name => {easy_baseline_for_id: nil})
    end
  end

  def find_entities
    @entities = @query.entities(:includes => [:project, :status, :assigned_to, :fixed_version, :tracker, :priority, :custom_values], :order => "#{Issue.table_name}.start_date", :preload => [:project, :author, :assigned_to, :relations_from, :relations_to])
  end

  def find_start_date
    @start_date = @query.entity.minimum(:start_date)
    if @start_date.nil? && (x = @query.entity.minimum(:due_date))
      @start_date = x - 1.day
    end
    @start_date ||= Date.today
  end

  def find_end_date
    @end_date = @query.entity.maximum(:start_date)
  end

  def authorize(ctrl = params[:controller], action = params[:action], global = false)
    if @project.nil? || @project.module_enabled?(:easy_gantt)
      super
    else
      non_gantt_project = @project
      @project = nil
      if super(ctrl, action, true)
        @project = non_gantt_project
        true
      else
        false
      end
    end
  end

  def find_optional_project
    #easy query workaround
    return if params[:set_filter] == '1' && params[:project_id] && params[:project_id].match(/\A(=|\!|\!\*|\*)\S*/)

    if params[:no_turn_on_check] == '1'
      @project = Project.visible.find(params[:project_id]) unless params[:project_id].blank?
    else
      super
    end
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

easy_gantt/app/helpers/easy_gantts_helper.rb
module EasyGanttsHelper

  def easy_gantt_js_button(text, options={})
    if text.is_a?(Symbol)
      text = l(text, :scope => [:easy_gantt, :button])
      options[:title] ||= l(text, :scope => [:easy_gantt, :title], :default => text)
    end
    options[:class] = "gantt_button #{options[:class]}"
    options[:class] << ' button button-2' unless options.delete(:no_button)
    if (icon = options.delete(:icon))
      options[:class] << " icon #{icon}"
    end
    link_to(text, options[:url] || 'javascript:void(0)', options)
  end

  def easy_gantt_help_button(*args)
    options = args.extract_options!
    feature = args.shift
    text = args.shift

    options[:class] = "gantt-help-button #{options[:class]}"
    options[:icon] ||= 'icon-help'
    options[:id] = feature.to_s + '_help'
    easy_gantt_js_button(text || '&#8203;'.html_safe, options) + %Q(
    <div id="#{feature}_help_modal" style="display:none">
      <h3 class="title">#{raw l(:heading, :scope => [:easy_gantt, :popup, feature]) }</h3>
      <p>#{raw l(:text, :scope => [:easy_gantt, :popup, feature]) }</p>
     </div>
    ).html_safe
  end
end

easy_gantt/app/views/easy_gantt/_includes.html.erb
<% heads_for_wiki_formatter %>
<%= content_for :header_tags do %>
  <%= stylesheet_link_tag(:dhtmlxgantt, :plugin => 'easy_gantt', :media => 'all') %>
  <%= stylesheet_link_tag(:easy_gantt, :plugin => 'easy_gantt', :media => 'all') %>
  <%= javascript_include_tag(:dhtmlxgantt, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:dhtmlxgantt_marker, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:easy_gantts, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:data, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:loader, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:saver, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:logger, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:test, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:widget, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:panel_widget, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:gantt_widget, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:libs, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:view, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:history, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:dhtml_modif, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:dhtml_addons, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:dhtml_rewrite, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:background, :plugin => 'easy_gantt') %>
  <%= javascript_include_tag(:pro_manager, :plugin => 'easy_gantt') %>
<% end %>

easy_gantt/app/views/easy_gantt/_menu_graph.html.erb
<div id="supertop_panel" class="clear"></div>
<div id="easy_gantt_menu" class="easy-gantt-menu clear">
  <div class="clear">
    <div class="push-left">
      <% if Rails.env.development? %>
        <span id="button_test" class="selected">
          <%= easy_gantt_js_button(l(:button_test)) %>
        </span>
      <% end %>

      <span id="button_jump_today">
        <%= easy_gantt_js_button('&#8203;'.html_safe, :title => l(:jump_today, :scope => [:easy_gantt, :title]), :icon => 'icon-calendar') %>
      </span>
      <% {'day' => 'calendar-day', 'week' => 'calendar-week', 'month' => 'calendar-month'}.each do |x, i| %>
        <div id="button_<%= x %>_zoom" class="menu-item">
          <%= easy_gantt_js_button(:"#{x}_zoom", :icon => "icon-#{i}") %>
        </div>
      <% end %>
    </div>
    <div class="push-right">
      <% menu_items_for(:easy_gantt, @project) do |node| %>
        <% opts = node.html_options.dup; opts[:url] = (node.url.is_a?(Proc) ? node.url.call(@project) : node.url) %>
        <div id="button_<%= node.name %>" class="menu-item">
          <% if opts.delete(:trial) %>
            <%= easy_gantt_help_button(node.name, node.caption, opts) %>
          <% else  %>
            <%= easy_gantt_js_button(node.caption, opts) %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <%= call_hook(:view_easy_gantts_issues_toolbars, {:project => @project}) %>
</div>
<!-- This is container for gantt-->
<div id="gantt_cont" style="width:100%;" class="clear"></div>
<!-- End container for gantt-->

easy_gantt/app/views/easy_gantt/issues.html.erb
<div id="easy_gantt" class="<%= defined?(EasyExtensions) ? 'easy' : 'redmine' %> gantt easy-content-page clear">
  <%= render @query, :easy_query_name => l(:heading_easy_gantts_issues), :wrapper_class => '' %>

  <%= render :partial => 'menu_graph' %>

  <div id="easy_gantt_footer">

    <div id="gantt_footer_buttons" class="easy-gantt-menu">
      <p id="button_print">
        <%= easy_gantt_js_button(l(:button_print), :icon => 'icon-print') %>
      </p>
      <p id="button_sample">
        <%= easy_gantt_js_button(:load_sample_data) %>
      </p>
    </div>
    <%= content_tag(:p, link_to(l(:text_easy_gantt_footer), l(:link_easy_gantt_plugin), :target => '_blank')) unless defined?(EasyExtensions) %>
  </div>
</div>
<%= render :partial => 'includes' %>

<%= content_for :header_tags do %>
  <script type="text/javascript">
    window.ysy = window.ysy || {};
    ysy.settings = ysy.settings || {};
    $.extend(true,ysy.settings,{
      easyRedmine: <%= defined?(EasyExtensions) ? true : false %>,
      <% if @project %>
      project: <%= "{'id': '#{@project.id}', 'name': '#{@project.name.html_safe}'}".html_safe %>,
      <% end %>
      nonWorkingWeekDays: <%= EasyGantt.non_working_week_days.to_json.html_safe %>,
      dateFormat: '<%=j Setting.date_format %>',
      withSample: <%= params[:sample] ? params[:sample] : 0 %>,
      holidays: [],
      paths: {
        rootPath: '<%= home_path %>',
      <% if @project %>
        mainGantt: "<%= issues_easy_gantt_path(@project, :format => 'json', :key => User.current.api_key)%>",
       <% else %>
        mainGantt: "<%= projects_easy_gantt_path(:format => 'json', :key => User.current.api_key) %>",
       <% end %>
        projectGantt: "<%= issues_easy_gantt_path(':projectID', params.merge(:format => 'json', :no_turn_on_check => 1, :key => User.current.api_key).except!(:controller, :action)).html_safe %>",
        issuePOST: "<%= issues_path(:format => 'json', :key => User.current.api_key) %>",
        issuePUT: "<%= issue_path(':issueID', :format => 'json', :key => User.current.api_key) %>",
        issueDELETE: "<%= issue_path(':issueID', :format => 'json', :key => User.current.api_key) %>",
        relationPOST: "<%= issue_relations_path(':issueID', :format => 'json', :key => User.current.api_key) %>",
        relationPUT: "<%= relation_easy_gantt_path(':projectID',':relaID', :format => 'json', :key => User.current.api_key) %>",
        relationDELETE: "<%= url_for(:id => ':relaID', :controller => :issue_relations, :action => :destroy, :format => 'json', :key => User.current.api_key, :only_path => true)%>",
        versionPOST: "<%= project_versions_path(':projectID', :format => 'json', :key => User.current.api_key) %>",
        versionPUT: "<%= version_path(':versionID', :format => 'json', :key => User.current.api_key) %>",
        sample_data: "<%= home_path %>plugin_assets/easy_gantt/javascripts/sample_{{version}}.json"
      },
      labels: {
        buttons: {
          button_delete: '<%= l(:button_delete) %>',
          button_submit: '<%= l(:button_submit) %>',
          button_cancel: '<%= l(:button_cancel) %>',
          button_reload: '<%= l(:reload, :scope => [:easy_gantt, :button]) %>',
          button_save: '<%= l(:button_save) %>'
        },
        types:{
          project:'<%= l(:field_project) %>',
          issue:'<%= l(:field_issue) %>',
          milestone:'<%= l(:field_version) %>',
          relation:'<%= l(:field_relation) %>'
        },
        sample_text: '<%= l(:text, :scope => [:easy_gantt, :sample]).html_safe %>',
        sample_global_free_text:'<%= l(:text, :scope => [:easy_gantt, :sample_global_free]).html_safe %>',
        date: {
          month_full: <%=raw l('date.month_names').compact.to_json %>,
          month_short: <%=raw l('date.abbr_month_names').compact.to_json %>,
          day_full: <%=raw l('date.day_names').compact.to_json %>,
          day_short: <%=raw l('date.abbr_day_names').compact.to_json %>
        },
        link_dir: {
          link_start: "<%= l(:link_start, :scope => [:easy_gantt, :link_dir]) %>",
          link_end: "<%= l(:link_end, :scope => [:easy_gantt, :link_dir]) %>"
        },
        errors: <%=raw l('activerecord.errors.messages').compact.to_json %>,
        errors2:{
          unsaved_parent:'<%= l(:unsaved_parent, :scope => [:easy_gantt, :errors]) %>',
          loop_link:'<%= l(:loop_link, :scope => [:easy_gantt, :errors]) %>',
          link_target_new:'<%= l(:link_target_new, :scope => [:easy_gantt, :errors]) %>',
          unsupported_link_type:'<%= l(:unsupported_link_type, :scope => [:easy_gantt, :errors]) %>',
          duplicate_link:'<%= l(:duplicate_link, :scope => [:easy_gantt, :errors]) %>'
        },
        gateway:{
          sendFailed:"<%= l(:send_failed, :scope => [:easy_gantt, :gateway]) %>",
          entitySaveFailed:"<%= l(:entity_save_failed, :scope => [:easy_gantt, :gateway]) %>",
          allSended:"<%= l(:notice_successful_update) %>"
        }
      }
    });
    $(document).ready(function () {
      $("p.nodata").remove()
    })
  </script>
  <script type="text/javascript">
    window.ysy = window.ysy || {};
    ysy.view = ysy.view || {};
    ysy.view.templates = $.extend(ysy.view.templates,{
    TaskTooltip:
      '<div class="name"><b>{{name}}</b></div>\
      <div class="start_date"><%= l(:field_start_date) %>: <strong>{{start_date}}</strong></div>\
      {{#end_date}}\
      <div class="end_date"><%= l(:field_due_date) %>: <strong>{{end_date}}</strong></div>\
      {{/end_date}}\
      {{#assignee}}\
      <div class="assignee"><%= l(:field_assigned_to) %>: <strong>{{assignee}}</strong></div>\
      {{/assignee}}\
      {{#problems}}\
      {{#overmilestone}}\
      <div class="tooltip-problem"><%= l(:overmile, :scope => [:easy_gantt, :errors]) %></div>\
      {{/overmilestone}}\
      {{#too_short}}\
      <div class="tooltip-problem"><%= l(:too_short, :scope => [:easy_gantt, :errors]) %></div>\
      {{/too_short}}\
      {{/problems}}\
    ',
    LinkConfigPopup:
      "<h3 class='title'><%= l(:heading_delay_popup) %></h3> <label for='link_delay_input'><%= l(:field_delay) %>:</label><input id='link_delay_input' type='number' min='0' value='{{delay}}' size='3'><hr>\
      <a id='link_delete' class='icon icon-del button'  href='javascript:void(0)'><%= l(:button_delete) %></a>\
      <a id='link_close' class='icon icon-save button-positive'  href='javascript:void(0)' style='float:right'><%= l(:button_submit) %></a>\
    ",
    SuperPanel:'\
    {{#sample}}\
    <div id="sample_cont" class="flash notice">\
    <h2 id="sample_label"><%= l(:header, :scope => [:easy_gantt, :sample]) %></h2>\
    <p>{{{text}}}</p>\
    \
    <p class="" style="text-align:center">\
    <a id="sample_video_button" class="icon youtube-icon" href="javascript:void(0)"><%= l(:video_label, :scope => [:easy_gantt, :sample]) %></a>\
    {{^global_free}}\
    <a id="sample_close_button" class="button button-important" href="javascript:void(0)" title="<%= l(:close_label, :scope => [:easy_gantt, :sample]).html_safe %>"><%= l(:close_label, :scope => [:easy_gantt, :sample]).html_safe %></a>\
    {{/global_free}}\
    {{#global_free}}\
    <a id="sample_upgrade_button" class="button button-positive" href="<%= l(:link_easy_gantt_plugin).html_safe %>" target="_blank" title="<%= l(:label_pro_upgrade, :scope => [:easy_gantt]) %>"><%= l(:label_pro_upgrade, :scope => [:easy_gantt]) %></a>\
    {{/global_free}}\
    </p>\
    <div class="clear"></div>\
    </div>\
    {{/sample}}\
    ',
    Button:'<span class="button {{active}}" title="{{title}}"><a id="{{elid}}_button_in" class="gantt_button{{icon}}" href="javascript:void(0)" >{{name}}</a></span>',
    LinkButton:'<a class="{{css}}" title="{{title}}" href="javascript:void(0)">{{name}}</a>',
    easy_unimplemented:'<h3 class="title">{{modal.title}}</h3><span>{{{modal.text}}}</span>',
    video_modal:'<h3 class="title"><%= l(:title, :scope => [:easy_gantt, :sample, :video]) %></h3>\
      <iframe class="modal_video" width="800" height="450"\
      src="//www.youtube.com/embed/<%= l(:video_id, :scope => [:easy_gantt, :sample, :video]) %>?autoplay=1">\
      </iframe>\
      <p><%= l(:text, :scope => [:easy_gantt, :sample, :video]) %></p>\
    ',
    video_modal_global:'<h3 class="title"><%= l(:title, :scope => [:easy_gantt, :sample_global_free, :video]) %></h3>\
      <iframe class="modal_video" width="800" height="450"\
      src="//www.youtube.com/embed/<%= l(:video_id, :scope => [:easy_gantt, :sample_global_free, :video]) %>?autoplay=1">\
      </iframe>\
      <p><%= l(:text, :scope => [:easy_gantt, :sample_global_free, :video]) %></p>\
    '
    });
  </script>
<% end %>

<%= call_hook(:view_easy_gantts_issues_bottom, {:project => @project}) %>

<% content_for :sidebar do %>
  <%= call_hook(:view_easy_gantts_issues_sidebar, {:project => @project, :query => @query}) %>
<% end %>